[site]
title = "Yucheng (Jeremy) Lin"
description = "Master student at University of California, San Diego."
favicon = "/favicon.svg"
last_updated = "July 8, 2026"

[author]
name = "Yucheng (Jeremy) Lin"
title = "Master Student"
institution = "University of California, San Diego"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "yul235@ucsd.edu"
location = "La Jolla, California"
location_url = "https://maps.app.goo.gl/oMCWr5CgJ69aAhMH7"
location_details = [
  "9500 Gilman Dr",
  "La Jolla, California, United States of America"
]
google_scholar = ""
orcid = ""
github = "https://github.com/Jeremy-lyc"
linkedin = "https://www.linkedin.com/in/yucheng-lin-720007253/"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

# Uncomment it if we have publications
# [[navigation]]
# title = "Publications"
# type = "page"
# target = "publications"
# href = "/publications"

# [[navigation]]
# title = "Teaching"
# type = "page"
# target = "teaching"
# href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

# [[navigation]]
# title = "Services"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
